This is makeindex, version 2.17 [TeX Live 2025/dev] (kpathsea + Thai support).
Scanning style file ./output/main.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file output/main.acn....done (122 entries accepted, 0 rejected).
Sorting entries....done (870 comparisons).
Generating output file output/main.acr....done (57 lines written, 0 warnings).
Output written in output/main.acr.
Transcript written in output/main.alg.
