This is makeindex, version 2.17 [TeX Live 2025/dev] (kpathsea + Thai support).
Scanning style file ./tesi.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file tesi.acn....done (64 entries accepted, 0 rejected).
Sorting entries....done (389 comparisons).
Generating output file tesi.acr....done (45 lines written, 0 warnings).
Output written in tesi.acr.
Transcript written in tesi.alg.
